### ISSUE TITLE
[README] Instructions to install dependencies are too sparse (and no longer current?)

### ISSUE THREAD

**Issue by KurtPfeifle** [jesparza/peepdf#46]
Trying to get a fully-featured PeepDF.py run on a current Debian Jessie (as well as on Mac OS X -- but I'll not go into depth with this OS here). **Problem:** **_getting the dependencies on libemu and PyV8 installed.**_
## Debian

To install the libemu and lxml dependencies worked like this:

```
 sudo apt-get install libemu2 python-libemu python-lxml libxml2
```

Getting the PyV8 dependency was successfull only partially. A V8 package is available:

```
 sudo apt-get install libv8-3.14.5
```

However, the PyV8 is no longer maintained on Google Code (http://code.google.com/p/pyv8/). The latest prebuilt (non-Windows) binaries there are from 2010 and are based on Python-2.6 (while Debian Jessie uses Python-2.7 now).

Trying it with 

```
 sudo pip install -v pyv8
```

 leads to the following error message:

```
src/Wrapper.cpp: In static member function ‘static void CPythonObject::SetupObjectTemplate(v8::Handle<v8::ObjectTemplate>)’:

src/Wrapper.cpp:311:84: error: invalid conversion from ‘v8::Handle<v8::Boolean> (*)(v8::Local<v8::String>, const v8::AccessorInfo&)’ to ‘v8::NamedPropertyQuery {aka v8::Handle<v8::Integer> (*)(v8::Local<v8::String>, const v8::AccessorInfo&)}’ [-fpermissive]

   clazz->SetNamedPropertyHandler(NamedGetter, NamedSetter, NamedQuery, NamedDeleter);
                                                                                    ^
In file included from src/Exception.h:6:0,
                 from src/Wrapper.h:8,
                 from src/Wrapper.cpp:1:
/usr/include/v8.h:2414:8: note: initializing argument 3 of ‘void v8::ObjectTemplate::SetNamedPropertyHandler(v8::NamedPropertyGetter, v8::NamedPropertySetter, v8::NamedPropertyQuery, v8::NamedPropertyDeleter, v8::NamedPropertyEnumerator, v8::Handle<v8::Value>)’
   void SetNamedPropertyHandler(NamedPropertyGetter getter,
        ^
src/Wrapper.cpp:312:94: error: invalid conversion from ‘v8::Handle<v8::Boolean> (*)(uint32_t, const v8::AccessorInfo&) {aka v8::Handle<v8::Boolean> (*)(unsigned int, const v8::AccessorInfo&)}’ to ‘v8::IndexedPropertyQuery {aka v8::Handle<v8::Integer> (*)(unsigned int, const v8::AccessorInfo&)}’ [-fpermissive]
   clazz->SetIndexedPropertyHandler(IndexedGetter, IndexedSetter, IndexedQuery, IndexedDeleter);
                                                                                              ^
In file included from src/Exception.h:6:0,
                 from src/Wrapper.h:8,
                 from src/Wrapper.cpp:1:
/usr/include/v8.h:2437:8: note: initializing argument 3 of ‘void v8::ObjectTemplate::SetIndexedPropertyHandler(v8::IndexedPropertyGetter, v8::IndexedPropertySetter, v8::IndexedPropertyQuery, v8::IndexedPropertyDeleter, v8::IndexedPropertyEnumerator, v8::Handle<v8::Value>)’
   void SetIndexedPropertyHandler(IndexedPropertyGetter getter,
        ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-8XX3Id/pyv8/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DQ9h7E-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-8XX3Id/pyv8
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

Debugging and possibly solving this is beyond my capabilities.

The next alternative, using the pyv8 sources from Google Code with

```
 python setup.py build
 sudo python setup.py install
```

completes without obvious error, but does not lead to final success either: Because when running `peepdf.py`, there is still the message 

**`Warning: PyV8 is not installed!!`**

**Comment by jesparza** [comment]
Hi @KurtPfeifle,

I just committed (https://github.com/jesparza/peepdf/commit/c74dc65c0ac7e506bae4f2582a2435ec50741f40) some changes in the readmes so you can find updated information. Besides using the PyPy package you can also use @buffer repos to install PyV8 and pylibemu.
- PyV8
  
  https://github.com/buffer/pyv8
  
  git clone https://github.com/buffer/pyv8.git
  cd pyv8
  python setup.py build
  sudo python setup.py install
  cd ..
  rm -rf pyv8
- pylibemu
  
  https://github.com/buffer/libemu
  https://github.com/buffer/pylibemu
  
  git clone https://github.com/buffer/libemu.git
  autoreconf -v -i
  ./configure --prefix=/opt/libemu
  sudo make install
  sudo pip install pylibemu
